org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
kapt.incremental=true
kapt.use.worker.api=true
android.enableR8=true
android.minSdkVersion=26
android.targetSdkVersion=34
android.compileSdkVersion=34
android.buildToolsVersion=34.0.0
APP_VERSION_CODE=1
APP_VERSION_NAME=1.0.0
